# Generated by Django 4.2 on 2023-04-07 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='blocklands.game')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('coins', models.CharField(max_length=255)),
                ('passes', models.ManyToManyField(blank=True, related_name='users', to='blocklands.pass')),
            ],
        ),
        migrations.AddField(
            model_name='pass',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_passes', to='blocklands.user'),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='blocklands.user'),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_color', models.CharField(max_length=7)),
                ('torso_color', models.CharField(max_length=7)),
                ('right_arm_color', models.CharField(max_length=7)),
                ('left_arm_color', models.CharField(max_length=7)),
                ('right_leg_color', models.CharField(max_length=7)),
                ('left_leg_color', models.CharField(max_length=7)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='blocklands.user')),
            ],
        ),
    ]
