# Generated by Django 4.2 on 2023-04-07 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocklands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passes',
        ),
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
        migrations.CreateModel(
            name='UserPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_at', models.DateTimeField(auto_now_add=True)),
                ('passs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocklands.pass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_passes', to='blocklands.user')),
            ],
        ),
    ]
