# Generated by Django 4.2 on 2023-04-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocklands', '0006_alter_avatar_avatar_alter_game_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='avatar',
            new_name='user',
        ),
    ]
